output_device: Elektron Syntakt
output_channel: 9
zero_indexed_countdown: true
slots:
  'A':
    loop_file: '[Empty 4 bars]'
    repeat_count: 1
    next_slot: 'B'
  'B':
    loop_file: Rappers Delight - bass - Electric Bass finger - bars 13-16
    repeat_count: 3
    next_slot: 'C'
  'C':
    loop_file: Seven Nation Army With Bass Guitar - bass - Jack White Bass Immitation - bars 1-4
    repeat_count: 2
    next_slot: 'B'
